#ifndef __ALL_Hpp_
#define __ALL_Hpp__

#include<iostream>
#include<iterator>
#include<barrier>
#include<atomic>
#include<algorithm>
#include<any>
#include<array>
#include<bitset>
#include<complex>
#include<bit>
//#include<coroutine>
#include<format>
#include<future>
#include<concepts>
#include<mutex>
#include<functional>
#include<chrono>
#include<compare>
#include<charconv>
#include<list>
#include<deque>
#include<stack>
#include<codecvt>
#include<limits>
#include<queue>
#include<thread>
#include<numeric>
#include<numbers>
//#include<execution>
#include<exception>
#include<semaphore>
#include<memory>
#include<initializer_list>
//#include<hash_map>
//#include<hash_set>
#include<filesystem>
#include<condition_variable>
#include<map>
#include<valarray>
#include<variant>
#include<vector>
#include<version>
#include<ranges>
#include<optional>
#include<string>
#include<streambuf>
#include<stdexcept>
#include<stacktrace>
#include<span>
#include<spanstream>
#include<shared_mutex>
#include<scoped_allocator>
#include<ratio>
#include<new>
#include<memory_resource>
#include<locale>
#include<latch>
#include<iomanip>


#endif